POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Ensure everything works, post to Mongo",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "testing notes url",
    "important": true,
    "userId": "6860b54d0fb645b04a5faee2"
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "adding new note to user",
    "important": true,
    "userId": "6860b54d0fb645b04a5faedf"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODYwYjU0ZDBmYjY0NWIwNGE1ZmFlZTIiLCJpYXQiOjE3NTEzMTI0NDV9.cUE4P4e-_19xGB3H_TYn2NZMmhUzeGkKYsXo2wuZmX4

{
    "content": "Creating note with Authorization: ",
    "important": true
}
